### ISSUE TITLE
Make autocfg available on conda-forge

### ISSUE THREAD

**Issue by giswqs** [zhreshold/autocfg#1]
It would be great to make autocfg available on conda-forge. Otherwise, downstream packages of autocfg can't be made available on conda-forge. Making it available on conda-forge will benefit all downstream packages and numerous conda-forge users. 

Relevant issue: https://github.com/autogluon/autogluon/issues/612

**Comment by arturdaraujo** [comment]
I fully agree! If any help is needed I'm here. Just a reminder that you only need to publish once, because the updates are automatically done. It's worth entering the conda-forge ecosystem.
@zhreshold

**Comment by giswqs** [comment]
Autocfg is now available on conda-forge. 
https://anaconda.org/conda-forge/autocfg
